# Generated by Django 4.1.2 on 2022-10-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='content',
            field=models.TextField(max_length=250),
        ),
    ]
